// frontend/src/components/layout/KbTabs.tsx
import { Link } from 'react-router-dom';

type KbTabKey = 'kp-list' | 'settings';

const TABS: Array<[KbTabKey, string]> = [
  ['kp-list', '知识点列表'],
  ['settings', '知识库设置'],
];

// Only the two tabs that actually have a page behind them — demo's
// kb-tabs also has a "回收站" tab, but that page has never been built in
// this project and no tracked issue owns it; adding a tab that 404s would
// be worse than omitting it (design doc §1, issue #13).
export function KbTabs({ kbId, active }: { kbId: number; active: KbTabKey }) {
  return (
    <div className="tabs kb-tabs">
      {TABS.map(([key, label]) => (
        <Link
          key={key}
          to={key === 'kp-list' ? `/knowledge-bases/${kbId}/knowledge-points` : `/knowledge-bases/${kbId}/settings`}
          className={`tab${key === active ? ' active' : ''}`}
        >
          {label}
        </Link>
      ))}
    </div>
  );
}

// frontend/src/views/knowledge-base/components/KbTabs.vue
<script setup lang="ts">
// 只放真实存在页面的两个 tab——demo 的 kb-tabs 还有「回收站」，但该页面
// 从未被建出且无 issue 跟踪；一个点了 404 的 tab 比不显示更糟（issue #13）。
type KbTabKey = 'kp-list' | 'settings'

const props = defineProps<{
  kbId: number
  active: KbTabKey
}>()

const TABS: Array<[KbTabKey, string]> = [
  ['kp-list', '知识点列表'],
  ['settings', '知识库设置'],
]

function linkFor(key: KbTabKey): string {
  return key === 'kp-list'
    ? `/knowledge-bases/${props.kbId}/knowledge-points`
    : `/knowledge-bases/${props.kbId}/settings`
}
</script>

<template>
  <div class="tabs kb-tabs">
    <RouterLink
      v-for="[key, label] in TABS"
      :key="key"
      :to="linkFor(key)"
      class="tab"
      :class="{ active: key === active }"
    >
      {{ label }}
    </RouterLink>
  </div>
</template>
